
default:
	gcc -Wall -Werror -I../include -o 3DChess legal_moves.c search.c evaluate.c game_tester.c log2.c ps.c

debug:
	gcc -Wall -Werror -g -I../include -o 3DChess legal_moves.c search.c evaluate.c game_tester.c log2.c ps.c
